namespace Dotsesses.Services;

/// <summary>
/// Static list of Muppet character names from Muppet Wiki.
/// </summary>
public static class MuppetNames
{
    public static readonly string[] Names = new[]
    {
        "Kermit the Frog",
        "Miss Piggy",
        "Fozzie Bear",
        "Gonzo the Great",
        "Rowlf the Dog",
        "Scooter",
        "Animal",
        "Pepe the King Prawn",
        "Rizzo the Rat",
        "Walter",
        "Dr. Teeth",
        "Floyd Pepper",
        "Janice",
        "Zoot",
        "Lips",
        "Dr. Bunsen Honeydew",
        "Beaker",
        "The Swedish Chef",
        "Statler",
        "Waldorf",
        "Sam Eagle",
        "Camilla the Chicken",
        "Uncle Deadly",
        "Bobo the Bear",
        "Robin the Frog",
        "Sweetums",
        "Lew Zealand",
        "Crazy Harry",
        "Beauregard",
        "Link Hogthrob",
        "The Newsman",
        "Pops",
        "Marvin Suggs",
        "Clifford",
        "Andy Pig",
        "Randy Pig",
        "Annie Sue",
        "Bean Bunny",
        "Big Mean Carl",
        "Constantine",
        "Denise",
        "Dr. Julius Strangepork",
        "Emily Bear",
        "Foo-Foo",
        "Gloria Estefan Penguin",
        "Nicky Napoleon",
        "Summer Penguin",
        "Winky Pinkerton",
        "Astoria",
        "Baskerville the Hound",
        "Beautiful Day Monster",
        "Behemoth",
        "Beverly Plume",
        "Bill the Bubble Guy",
        "Bobby Benson",
        "Bubba the Rat",
        "Butch",
        "Chester the Rat",
        "Chip",
        "Dead Tom",
        "Digit",
        "Doglion",
        "Droop",
        "Fleet Scribbler",
        "Fletcher Bird",
        "Flower-Eating Monster",
        "Forcryingoutloud Bird",
        "Frankie",
        "Gaffer",
        "George the Janitor",
        "Geri the Giraffe",
        "Gorgon Heap",
        "Hilda",
        "J.P. Grosse",
        "Jacques Roach",
        "Johnny Fiama",
        "Lenny the Lizard",
        "Lips",
        "Lubbock Lou",
        "Mildred Huxtetter",
        "Miss Mousey",
        "Muppy",
        "Murray the Minstrel",
        "Nigel",
        "Old Tom",
        "Patrol Bear",
        "Polly Lobster",
        "Quongo",
        "Sal Minella",
        "Seymour the Elephant",
        "Shakey Sanchez",
        "Snookie Blyer",
        "Sopwith the Camel",
        "Spamela Hamderson",
        "Thog",
        "Timmy Monster",
        "T.R. the Rooster",
        "Trumpet Girl",
        "Wayne",
        "Wanda",
        "Yolanda Rat",
        "Zelda Rose",
        "Angus McGonagle",
        "Boppity",
        "Bruno",
        "Catgut",
        "Clueless Morgan",
        "Gladys",
        "Koozebane Creature",
        "Mahna Mahna",
        "Mean Mama",
        "Mulch",
        "Mutations",
        "The Great Gonzo",
        "Veterinarian's Hospital Nurse Piggy",
        "Veterinarian's Hospital Nurse Janice"
    };
}
