[project]
name = "violin-swarm-plots"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "seaborn>=0.13.0",
    "matplotlib>=3.8.0",
    "numpy>=1.26.0",
    "pandas>=2.1.0",
    "scipy>=1.11.0",
]
